version: '3'
services:
  codecept-test:
    image: codeceptplaywrightjs
    build: .
    container_name: codeceptplaywright_docker
    ports:
      - "8080:80" # Map container's port 80 to host's port 8080
    volumes:
      - ./:/tests